In [ ]:
#python programming is made easier ana more convinent for programmers due
#its reusability
#python library is a group of interconnected modules.it contains code bundles that can be reused
#in different programs

In [ ]:
#benfits of python libraries

#easy to learn
#open source
#efficient and multu-platform support
#integrates well with enterprise apps and systems

In [ ]:
#breief about the libraries

#numpy:-numpy is numerical python which can handle the multidimensional matrices and data
#pandas:-it is mostly for the data analysis and data manipulation
##matplotlib and seaborn these both are for the vizualization purpose
#and these matplotlib and seaborn are used to create charts and pictures


In [ ]:
#import keyword this pacakages are imported with

In [ ]:
import math

a=16

print(math.sqrt(a))

4.0


In [ ]:
#IN the above example we have worked with the one of the method sqrt.
#if we directly importing the sqrt from the math module will also work


In [ ]:
from math import sqrt,sin

In [ ]:
a=16
b=60

print(sqrt(a))
print(sqrt(b))

4.0
7.745966692414834


In [ ]:
#numpy lets start
#numpy numpy numpy numpy numpy

#numpy numpy numpy numpy


In [ ]:
#advantages of numpy

#it privides an array object that is faster than python lists
#numpy povides supporting functions
#

In [ ]:
#import numpy as np
#means np is the alias name or the short cut name which we are giving to numpy
#so in plsce of numpy we can use np
#array() function which used for the creation of arrays

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
type(array)

numpy.ndarray

In [ ]:
import numpy

In [ ]:
array=numpy.array([1,4879,9784,4879,4,8,7])
print(array)

[   1 4879 9784 4879    4    8    7]


In [ ]:
import numpy as canada

In [ ]:
array=canada.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [ ]:
# 0-D arrays indicate the each value in an array is 0-D array

import numpy as np

arr=np.array(60)
print(arr)

60


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#this is an 1d array
array=np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [ ]:
type(array)

numpy.ndarray

In [ ]:
#this is an 2d array
array_2=np.array([[10,20,30,40],[50,60,70,80]])
print(array_2)

[[10 20 30 40]
 [50 60 70 80]]


In [ ]:
#lets see the 3d array now

In [ ]:
import numpy as np

array3=np.array([[[10,20,30,40],[50,60,70,80]],[[12,13,14,15],[16,17,18,19]]])

In [ ]:
print(array3)

[[[10 20 30 40]
  [50 60 70 80]]

 [[12 13 14 15]
  [16 17 18 19]]]


In [ ]:
type(array3)

numpy.ndarray

In [ ]:
#ndim is the function which is used to find the dimensions in which dimwnsion the data is in

In [ ]:
print(array3)
print(array3.ndim)

[[[10 20 30 40]
  [50 60 70 80]]

 [[12 13 14 15]
  [16 17 18 19]]]
3


In [ ]:
print(array_2)
print(array_2.ndim)

[[10 20 30 40]
 [50 60 70 80]]
2


In [ ]:
print(array)
print(array.ndim)

[1 2 3 4]
1


In [ ]:
#brod casting refers to the numpys ability to handle array of different shapes during arthematic operations

In [ ]:
a=np.array([[11,22,33],[10,20,30]])
print(a)



[[11 22 33]
 [10 20 30]]


In [ ]:
b=4
print(b)

4


In [ ]:
c=a+b
print(c)

[[15 26 37]
 [14 24 34]]


In [ ]:
#functions of numpy module

#numpy array functions

#numpy.reshape()
#numpy.concatenate()
#numpy.shape()

In [ ]:
print(array3)

[[[10 20 30 40]
  [50 60 70 80]]

 [[12 13 14 15]
  [16 17 18 19]]]


In [ ]:
print(array3.shape)

(2, 2, 4)


In [ ]:
print(array_2)

[[10 20 30 40]
 [50 60 70 80]]


In [ ]:
#shape is used to return the number of rows and columns in a array
#shape function is a part of numpy
print(array_2.shape)

(2, 4)


In [ ]:
#reshape() function
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
array=array.reshape(6,2)
print(array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
#concatenate

array1=np.array([10,20,25])
array2=np.array([30,40,50])
print(array1)
print(array2)

[10 20 25]
[30 40 50]


In [ ]:
arr=np.concatenate((array1,array2))
print(arr)

[10 20 25 30 40 50]


In [ ]:
#numpy string functions

a=np.array(['Hello','World'])
b=np.array(['welcome','learners'])

print(a)
print(b)

result=np.char.add(a,b)
print(result)

['Hello' 'World']
['welcome' 'learners']
['Hellowelcome' 'Worldlearners']


In [ ]:
#
array="hello how are you"
print(array)

a=np.char.replace(array,'hello','meena')
print(a)

hello how are you
meena how are you


In [ ]:
#upper case and lower case

In [ ]:
upp=np.char.upper(array)
print(upp)

HELLO HOW ARE YOU


In [ ]:
#now lets convert this upper case to lower case

In [ ]:
lower=np.char.lower(upp)
print(lower)

hello how are you


In [ ]:
#arthematic functions in numpy
#04 jan 2024



In [1]:
import numpy as np


In [2]:
a=np.array([10,20,30])
b=np.array([20,30,40])
c=np.add(a,b)
print(c)

[30 50 70]


In [5]:
sub=np.subtract(b,a)
print(sub)

[10 10 10]


In [7]:
mod=np.mod(b,a)
print(mod)

[ 0 10 10]


In [9]:
a=np.array([2,2,3,4])
b=np.array([2,3,2,3])
result = np.power(a,b)
print(result)

[ 4  8  9 64]


In [ ]:
#numpy statistical functions


In [12]:
#median means first a fall its going to make the part into

a=np.array([1,3,4,5,6,7,8,9])
result=np.median(a)
print(result)

5.5


In [13]:
c=np.mean(a)
print(c)

5.375


In [ ]:
#indexing part



In [14]:
#taking the same example to print the element using the indexing
print(a[7])

9


In [15]:
num_inde=np.array(['gurwinder sir',"meena mam"])
print(num_inde)

['gurwinder sir' 'meena mam']


In [16]:
num_inde[1]

'meena mam'

In [18]:
print(a)

[1 3 4 5 6 7 8 9]


In [19]:
c=a[0]+a[1]
print(c)

4


In [21]:
y=np.array([[10,20,30,40,50],[50,60,70,80,90]])
print(y)

[[10 20 30 40 50]
 [50 60 70 80 90]]


In [22]:
y[0]

array([10, 20, 30, 40, 50])

In [23]:
y[1]

array([50, 60, 70, 80, 90])

In [28]:
y[0,1:3]

array([20, 30])

In [ ]:
#with these also we can perform the addition and substraction

In [29]:
y[0,1]+y[1,2]

90

In [31]:
#three dimensional example of the numpy
y=np.array([[[10,20,30,40,50],[50,60,70,80,90]],[[10,20,30,40,50],[50,60,70,80,90]]])
print(y)


[[[10 20 30 40 50]
  [50 60 70 80 90]]

 [[10 20 30 40 50]
  [50 60 70 80 90]]]


In [32]:
y.ndim

3

In [33]:
y[0,1,4]

90

In [36]:
y[-1,-2,3]

40

In [ ]:
#slicing ,step size ,negative insexing which we have seen earlier is
#same here also in numpy there is no difference thats it


In [ ]:
#till now numpy has completed just pls
#from tomorrow lets start pandas 05 jan 2024 we wil start pandas